///\file
///\brief configuration for universalis, host unknown-microsoft-unknown.
/// This public configuration was not generated by an autoconfiguration script;
/// it was handwritten hardcoded for the following canonical host triplet:
/// - compiler: microsoft
/// - operating system: microsoft (it is unclear what other operating systems are supported by microsoft's compiler)
/// - architecture: it is unclear what architectures are supported by microsoft's compiler and operating system
#pragma once
