#pragma once
 
/* src/./diversalis/detail/configuration.hpp. Generated automatically at end of configure. */
/* src/./diversalis/detail/configuration.private.hpp.  Generated by configure.  */
/* see ./src/+autoheader.private.hpp.in for the -- commented -- file generated from configure.ac by autoheader. */

///\file
///\brief configuration for diversalis
#pragma once



#ifndef DIVERSALIS__STDC_HEADERS 
#define DIVERSALIS__STDC_HEADERS  1 
#endif
#ifndef DIVERSALIS__HAVE_STDINT_H 
#define DIVERSALIS__HAVE_STDINT_H  1 
#endif
#ifndef DIVERSALIS__HAVE_INTTYPES_H 
#define DIVERSALIS__HAVE_INTTYPES_H  1 
#endif

#ifndef DIVERSALIS__SIZEOF 
#define DIVERSALIS__SIZEOF  
#endif

#ifndef DIVERSALIS__SIZEOF_VOID_P 
#define DIVERSALIS__SIZEOF_VOID_P  4 
#endif

#ifndef DIVERSALIS__SIZEOF_LONG_LONG_INT 
#define DIVERSALIS__SIZEOF_LONG_LONG_INT  8 
#endif
#ifndef DIVERSALIS__SIZEOF_LONG_INT 
#define DIVERSALIS__SIZEOF_LONG_INT  4 
#endif
#ifndef DIVERSALIS__SIZEOF_INT 
#define DIVERSALIS__SIZEOF_INT  4 
#endif
#ifndef DIVERSALIS__SIZEOF_SHORT_INT 
#define DIVERSALIS__SIZEOF_SHORT_INT  2 
#endif
#ifndef DIVERSALIS__SIZEOF_CHAR 
#define DIVERSALIS__SIZEOF_CHAR  1 
#endif
#if !defined __CHAR_UNSIGNED__
/* #      undef __CHAR_UNSIGNED__ */
#endif

#ifndef DIVERSALIS__HAVE_LONG_DOUBLE 
#define DIVERSALIS__HAVE_LONG_DOUBLE  1 
#endif
#ifndef DIVERSALIS__SIZEOF_LONG_DOUBLE 
#define DIVERSALIS__SIZEOF_LONG_DOUBLE  12 
#endif
#ifndef DIVERSALIS__SIZEOF_DOUBLE 
#define DIVERSALIS__SIZEOF_DOUBLE  8 
#endif
#ifndef DIVERSALIS__SIZEOF_FLOAT 
#define DIVERSALIS__SIZEOF_FLOAT  4 
#endif

/* #undef DIVERSALIS__WORDS_BIGENDIAN */
 
