#! /bin/bash

##############################################################################
#
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2, or (at your option) any later version.
# copyright 1999-2007 psycledelics http://psycle.pastnotecut.org : johan boule
#
# sets the remote host name.
# sets the remote path.
# maps local user@host account names to remote user account names.
# note: this file is to be sourced.
#
# \meta generic
# \meta hook /build /debian/archive/build /microsoft/distribute
# \meta standard gnu
#
##############################################################################



#####################################################################
# queries the functions and exports the cached results in variables.
#####################################################################
function packageneric--remote
{
	local package_directory=$1 && shift &&
	
	####################
	# gets package name
	####################
	{
		local package__name=$($package_directory/packageneric/generic/bin/package.meta-information name)
	} &&

	#############################
	# determines local user@host
	#############################
	{
		##################
		# local host name
		##################
		# note: please configure you local host with a real public name to prevent clashes.
		{		
			local local__host=$(hostname --long || uname --nodename || echo $HOSTNAME)
		} &&

		####################################		
		# local user effective account name
		####################################
		{		
			local local__user=$(id --user --name || echo ${USER:-$LOGNAME})
		}
	} &&

	##########################################
	# calls configuration file hook functions
	##########################################
	{
		packageneric__remote__host=$(packageneric--remote--host $package__name $local__host $local__user) &&
		packageneric__remote__user=$(packageneric--remote--user $packageneric__remote__host $package__name $local__host $local__user)
		packageneric__remote__path=$(packageneric--remote--path $packageneric__remote__host $packageneric__remote__user $package__name $local__host $local__user)
	}
} &&

##################################
# sources the configuration files
##################################
{
	. $1/packageneric/package/remote/host &&
	. $1/packageneric/package/remote/user
} &&

packageneric--remote "$@"
