#! /bin/sh

##############################################################################
#
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2 of the License, or (at your option) any later version.
# Copyright (C) 2004-2005 Johan Boule <bohan.dyndns.org>
#
##############################################################################

export LC_ALL=C &&

#exec -a $(basename $0) $(dirname $0)/../colorizers/make "$@" 2>&1

#time
$(dirname $0)/../colorizers/make "$@" 2>&1
