/* ./packageneric/generic/detail/src/packageneric/package/configurations/autoconf/configuration.private.hpp.  Generated by configure.  */
/* see packageneric/+autogenerated/autotools/autoheader.private.hpp.in for the -- commented -- file generated from configure.ac by autoheader. */

///\file
///\brief packageneric configuration
#pragma once
#include "../../meta-information.private.hpp"



////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This configuration is for the following host environment:



///\name platform for which the source package was built (and hence for which this installation is), and compiler/linker options used.
///\{
	/// platform for which the source package was configured (and hence for which this installation is).
	#define PACKAGENERIC__CONFIGURATION__COMPILER__HOST "unkown-microsoft-unkown"
	/// compiler options used to build the source package.
	#define PACKAGENERIC__CONFIGURATION__COMPILER__CXXFLAGS "unkown"
	/// linker options used to build the source package.
	#define PACKAGENERIC__CONFIGURATION__COMPILER__LDFLAGS "unkown"
///\}



///\name installation paths
///\{
	/// absolute path to the bin dir
/* 	#undef PACKAGENERIC__CONFIGURATION__INSTALL_PATH__BIN */
	/// relative path from the bin dir to the lib dir
	#define PACKAGENERIC__CONFIGURATION__INSTALL_PATH__BIN_TO_LIB "../lib"
	/// relative path from the bin dir to the libexec dir
/* 	#undef PACKAGENERIC__CONFIGURATION__INSTALL_PATH__BIN_TO_LIBEXEC */
	/// relative path from the bin dir to the share dir
	#define PACKAGENERIC__CONFIGURATION__INSTALL_PATH__BIN_TO_SHARE "../share"
	/// relative path from the bin dir to the var dir
	#define PACKAGENERIC__CONFIGURATION__INSTALL_PATH__BIN_TO_VAR "../var"
	/// relative path from the bin dir to the etc dir
	#define PACKAGENERIC__CONFIGURATION__INSTALL_PATH__BIN_TO_ETC "../etc"
///\}



////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///\name build environment from which the source package was built (optional information not really needed).
///\{
	/// name of the operating system from which the source package was built $(uname --all)
	#define PACKAGENERIC__OPERATING_SYSTEM__UNAME "Linux dynamic--bohan 2.6.12-co-0.7.1-hn8 #8 Sat Dec 3 18:15:37 CET 2005 i686 GNU/Linux"
	/// tool chain used to build the source package.
	#define PACKAGENERIC__CONFIGURATION__COMPILER__BUILD "i686-pc-linux-gnu"
	/// who built the source package $(id --user --name)@$(hostname --long)
	#define PACKAGENERIC__OPERATING_SYSTEM__ID "bohan@dynamic--bohan.retropaganda.info"
///\}
