#include <packageneric/package.private.hpp>
#define PACKAGENERIC__MODULE__NAME "unkown"
#define PACKAGENERIC__CONFIGURATION__INSTALL_PATH__BIN_TO_LIB "../lib"
#define PACKAGENERIC__CONFIGURATION__INSTALL_PATH__BIN_TO_SHARE "../share"
#define PACKAGENERIC__CONFIGURATION__INSTALL_PATH__BIN_TO_VAR "../var"
#define PACKAGENERIC__CONFIGURATION__INSTALL_PATH__BIN_TO_ETC "../etc"

