#define PACKAGENERIC__PACKAGE__NAME "unkown"
#define PACKAGENERIC__PACKAGE__VERSION "unkown"
#define PACKAGENERIC__PACKAGE__VERSION__MAJOR 0
#define PACKAGENERIC__PACKAGE__VERSION__MINOR 0
#define PACKAGENERIC__PACKAGE__VERSION__PATCH 0

#define PACKAGENERIC__CONFIGURATION__COMPILER__HOST "qmake-unkown"
