#! /usr/bin/env bash

# glib2 package recipe for MinGW cross pkg tool.
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2, or (at your option) any later version.
# copyright 2008-2008 Johan Boule <bohan@jabber.org>

# http://library.gnome.org/devel/glib/unstable/glib-cross-compiling.html

set -eux

version_short=2.16
version=$version_short.3

case "$1" in

version)
    echo $version
    ;;

description)
    echo The GLib library of C routines
    ;;

deps)
    echo gcc gettext libiconv pkg-config
    ;;
    
download)
	tar tfj "glib-$version.tar.bz2" &>/dev/null ||
    wget -c "http://ftp.gnome.org/pub/GNOME/sources/glib/$version_short/glib-$version.tar.bz2"
    ;;

unpack)
    tar xfj "glib-$version.tar.bz2"
    ;;

build | continue-build)
    cd "glib-$version"
	case "$1" in
		build)
			echo glib_cv_long_long_format=I64 > win32.cache
			echo glib_cv_stack_grows=no >> win32.cache
			chmod a-w win32.cache # prevent configure from changing it
			./configure \
				--host="$TARGET" \
				--disable-shared \
				--prefix="$PREFIX/$TARGET" \
				--cache-file=win32.cache
			;;
	esac
    $MAKE install DESTDIR=$DESTDIR
	;;

clean-build)
    rm -Rf "glib-$version"
    ;;

esac
