#! /usr/bin/env bash

# jpeg package recipe for MinGW cross pkg tool.
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2, or (at your option) any later version.
# copyright 2008-2008 Johan Boule <bohan@jabber.org>
#
# Based on MinGW cross compiling environment, version 1.4
# copyright 2007-2008 Volker Grabsch <vog@notjusthosting.com>
# copyright 2007-2008 Rocco Rutte <pdmef@gmx.net>
# copyright 2007-2008 Andreas Roever <roever@users.sf.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject
# to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#---
#   jpeg
#
#   http://www.ijg.org/
#   http://packages.debian.org/unstable/source/libjpeg6b
#---

set -eux

VERSION_jpeg=6b

case "$1" in

version)
    echo $VERSION_jpeg
    ;;

new-version)
    VERSION=`
        wget -q -O- 'http://packages.debian.org/unstable/source/libjpeg6b' |
        $SED -n 's,.*libjpeg6b_\([0-9][^>]*\)\.orig\.tar.*,\1,p' | 
        tail -1`
    test -n "$VERSION"
    $SED "s,^VERSION_jpeg=.*,VERSION_jpeg=$VERSION," -i "$0"
    ;;

description)
    echo "The Independent JPEG Group's JPEG library"
    ;;

deps)
    echo gcc
    ;;
    
download)
    tar tfz "libjpeg6b_$VERSION_jpeg.orig.tar.gz" &>/dev/null ||
    wget -c "http://ftp.debian.org/debian/pool/main/libj/libjpeg6b/libjpeg6b_$VERSION_jpeg.orig.tar.gz"
    ;;

unpack)
    tar xfz "libjpeg6b_$VERSION_jpeg.orig.tar.gz"
    ;;

build | continue-build)
    cd "jpeg-$VERSION_jpeg"
	case "$1" in
		build)
			./configure \
				CC="$TARGET-gcc" RANLIB="$TARGET-ranlib" \
				--disable-shared \
				--prefix="$PREFIX/$TARGET"
			# jpeg doesn't use automake and its makefile doesn't support destdir.
			# We fix the install rules in the makefile.
			sed 's,\(\$(INSTALL_[^)]*) [^ ]* \)\(.*\),\1 \$\$DESTDIR/\2,' -i Makefile
			;;
	esac
	$MAKE
	# create the dest dirs since the makefile doesn't do it.
	install -d $DESTDIR/$PREFIX/$TARGET/{include,lib}
	$MAKE install-lib DESTDIR=$DESTDIR
	;;

clean-build)
    rm -Rf "jpeg-$VERSION_jpeg"
    ;;

esac
