#! /usr/bin/env bash

# libiconv package recipe for MinGW cross pkg tool.
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2, or (at your option) any later version.
# copyright 2008-2008 Johan Boule <bohan@jabber.org>
#
# Based on MinGW cross compiling environment, version 1.4
# copyright 2007-2008 Volker Grabsch <vog@notjusthosting.com>
# copyright 2007-2008 Rocco Rutte <pdmef@gmx.net>
# copyright 2007-2008 Andreas Roever <roever@users.sf.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject
# to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#---
#   libiconv
#
#   http://www.gnu.org/software/libiconv/
#---

set -eux

VERSION_libiconv=1.9.2

case "$1" in

version)
    echo $VERSION_libiconv
    ;;

new-version)
    VERSION=`
        wget -q -O- 'http://ftp.gnu.org/pub/gnu/libiconv/' |
        $SED -n 's,.*libiconv-\([0-9]*\)\.\([0-9]*\)\(\.[0-9]*\)\.tar.*,\1.\2\3,p' |
        sort | tail -1`
    test -n "$VERSION"
    $SED "s,^VERSION_libiconv=.*,VERSION_libiconv=$VERSION," -i "$0"
    ;;

description)
    echo GNU character encoding conversion library
    ;;

deps)
	# Notes from http://www.gnu.org/software/libiconv
	#
	# After installing GNU libiconv for the first time, it is recommended to recompile and reinstall GNU gettext,
	# so that it can take advantage of libiconv.
	#
	# On systems other than GNU/Linux, the iconv program will be internationalized
	# only if GNU gettext has been built and installed before GNU libiconv.
	#
	# This means that the first time GNU libiconv is installed, we have a circular dependency
	# between the GNU libiconv and GNU gettext packages, which can be resolved by building and installing either
	# * first libiconv, then gettext, then libiconv again,
	# or (on systems supporting shared libraries, excluding AIX)
	# * first gettext, then libiconv, then gettext again.
	#
    #echo gcc gettext
    echo gcc
    ;;
    
download)
    tar tfz "libiconv-$VERSION_libiconv.tar.gz" &>/dev/null ||
    wget -c "http://ftp.gnu.org/pub/gnu/libiconv/libiconv-$VERSION_libiconv.tar.gz"
    ;;

unpack)
    tar xfz "$DOWNLOAD/libiconv-$VERSION_libiconv.tar.gz"
    ;;

build | continue-build)
	cd "libiconv-$VERSION_libiconv"
	case "$1" in
		build)
			./configure \
				--host="$TARGET" \
				--prefix="$PREFIX/$TARGET" \
				--disable-shared \
				--disable-nls
			;;
	esac
	$MAKE install DESTDIR=$DESTDIR
	;;

clean-build)
    rm -Rf "libiconv-$VERSION_libiconv"
    ;;

esac
