#! /usr/bin/env bash

# pthreads-w32 package recipe for MinGW cross pkg tool.
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2, or (at your option) any later version.
# copyright 2008-2008 Johan Boule <bohan@jabber.org>
#
# Based on MinGW cross compiling environment, version 1.4
# copyright 2007-2008 Volker Grabsch <vog@notjusthosting.com>
# copyright 2007-2008 Rocco Rutte <pdmef@gmx.net>
# copyright 2007-2008 Andreas Roever <roever@users.sf.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject
# to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#---
#   pthreads-w32
#
#   http://sourceware.org/pthreads-win32/
#---

set -eux

VERSION_pthreads=2-8-0

case "$1" in

version)
    echo $VERSION_pthreads
    ;;

new-version)
    VERSION=`
        wget -q -O- 'ftp://sourceware.org/pub/pthreads-win32/Release_notes' |
        $SED -n 's,^RELEASE \([0-9][^[:space:]]*\).*,\1,p' | 
        tr '.' '-' |
        head -1`
    test -n "$VERSION"
    $SED "s,^VERSION_pthreads=.*,VERSION_pthreads=$VERSION," -i "$0"
    ;;

description)
    echo "library implementing the POSIX threads API on win32"
    ;;

deps)
    echo gcc
    ;;
    
download)
    tar tfz "pthreads-w32-$VERSION_pthreads-release.tar.gz" &>/dev/null ||
    wget -c "ftp://sourceware.org/pub/pthreads-win32/pthreads-w32-$VERSION_pthreads-release.tar.gz"
    ;;

unpack)
    tar xfz "pthreads-w32-$VERSION_pthreads-release.tar.gz"
    ;;

build | continue-build)
    cd "pthreads-w32-$VERSION_pthreads-release"
	case "$1" in
		build)
    		$SED '35i\#define PTW32_STATIC_LIB' -i pthread.h
			;;
	esac
    $MAKE GC-static CROSS="$TARGET-"
    install -d "$DESTDIR/$PREFIX/$TARGET/lib"
    install -m664 libpthreadGC2.a "$DESTDIR/$PREFIX/$TARGET/lib/libpthread.a"
    install -d "$DESTDIR/$PREFIX/$TARGET/include"
    install -m664 pthread.h sched.h semaphore.h "$DESTDIR/$PREFIX/$TARGET/include/"
	;;

clean-build)
    rm -Rf "pthreads-w32-$VERSION_pthreads-release"
    ;;

esac
