#! /usr/bin/env bash

# w32api package recipe for MinGW cross pkg tool.
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2, or (at your option) any later version.
# copyright 2008-2008 Johan Boule <bohan@jabber.org>
#
# Based on MinGW cross compiling environment, version 1.4
# copyright 2007-2008 Volker Grabsch <vog@notjusthosting.com>
# copyright 2007-2008 Rocco Rutte <pdmef@gmx.net>
# copyright 2007-2008 Andreas Roever <roever@users.sf.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject
# to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#---
#   MinGW Windows API
#
#   http://mingw.sourceforge.net/
#---

set -eux

VERSION_w32api=3.11

case "$1" in

version)
    echo $VERSION_w32api
    ;;

new-version)
    VERSION=`
        wget -q -O- 'http://sourceforge.net/project/showfiles.php?group_id=2435' |
        $SED -n 's,.*w32api-\([0-9][^>]*\)-src\.tar.*,\1,p' | 
        head -1`
    test -n "$VERSION"
    $SED "s,^VERSION_w32api=.*,VERSION_w32api=$VERSION," -i "$0"
    ;;

description)
    #echo ...
    ;;

deps)
    # none
    ;;
    
download)
    tar tfz "w32api-$VERSION_w32api.tar.gz" &>/dev/null ||
    wget -c "http://$(cat $RECIPES/mirrors/sourceforge)/mingw/w32api-$VERSION_w32api.tar.gz"
    ;;

unpack)
    build=$(pwd)
    install -d "$DESTDIR/$PREFIX/$TARGET"
    cd "$DESTDIR/$PREFIX/$TARGET"
    tar xfz "$build/w32api-$VERSION_w32api.tar.gz"
    # fix incompatibilities with gettext
    $SED 's,\(SUBLANG_BENGALI_INDIA\t\)0x01,\10x00,'    -i "$DESTDIR/$PREFIX/$TARGET/include/winnt.h"
    $SED 's,\(SUBLANG_PUNJABI_INDIA\t\)0x01,\10x00,'    -i "$DESTDIR/$PREFIX/$TARGET/include/winnt.h"
    $SED 's,\(SUBLANG_ROMANIAN_ROMANIA\t\)0x01,\10x00,' -i "$DESTDIR/$PREFIX/$TARGET/include/winnt.h"
    # fix incompatibilities with jpeg
    $SED 's,typedef unsigned char boolean;,,'           -i "$DESTDIR/$PREFIX/$TARGET/include/rpcndr.h"
    # fix missing definitions for WinPcap and libdnet
    $SED '1i\#include <wtypes.h>'                       -i "$DESTDIR/$PREFIX/$TARGET/include/iphlpapi.h"
    $SED '1i\#include <wtypes.h>'                       -i "$DESTDIR/$PREFIX/$TARGET/include/wincrypt.h"
    ;;

build | continue-build | clean-build)
    # not really built
    ;;

esac
