#! /usr/bin/env bash

# zlib package recipe for MinGW cross pkg tool.
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2, or (at your option) any later version.
# copyright 2008-2008 Johan Boule <bohan@jabber.org>
#
# Based on MinGW cross compiling environment, version 1.4
# copyright 2007-2008 Volker Grabsch <vog@notjusthosting.com>
# copyright 2007-2008 Rocco Rutte <pdmef@gmx.net>
# copyright 2007-2008 Andreas Roever <roever@users.sf.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject
# to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#---
#   zlib
#
#   http://www.zlib.net/
#---

set -eux

VERSION_zlib=1.2.3

case "$1" in

version)
    echo $VERSION_zlib
    ;;

new-version)
    VERSION=`
        wget -q -O- 'http://sourceforge.net/project/showfiles.php?group_id=5624' |
        $SED -n 's,.*zlib-\([0-9][^>]*\)\.tar.*,\1,p' | 
        head -1`
    test -n "$VERSION"
    $SED "s,^VERSION_zlib=.*,VERSION_zlib=$VERSION," -i "$0"
    ;;

description)
    echo compression library
    ;;

deps)
	echo gcc
    ;;
    
download)
    tar tfj "zlib-$VERSION_zlib.tar.bz2" &>/dev/null ||
    wget -c "http://$(cat $RECIPES/mirrors/sourceforge)/libpng/zlib-$VERSION_zlib.tar.bz2"
    ;;

unpack)
    tar xfj "zlib-$VERSION_zlib.tar.bz2"
    ;;

build | continue-build)
	cd "zlib-$VERSION_zlib"
	case "$1" in
		build)
			# zlib doesn't use autotools and its makefile doesn't support destdir.
			# We cheat by setting prefix to destdir (it's ok since there's no rpath nor abs symlinks).
			CC="$TARGET-gcc" RANLIB="$TARGET-ranlib" ./configure \
				--prefix="$DESTDIR/$PREFIX/$TARGET"
		;;
	esac
	$MAKE install DESTDIR=$DESTDIR
	;;

clean-build)
	rm -Rf "zlib-$VERSION_zlib"
	;;

esac
