#! /usr/bin/env waf

APPNAME = 'waf-test'
VERSION = '0.0.1'

srcdir = '.'

blddir = '++build'

def init():
	pass

def set_options(opt):
	opt.tool_options('compiler_cxx')

def configure(conf):
	conf.check_tool('compiler_cxx')
	
def build(bld):
	#bld.add_subdirs('../diversalis')

	p = bld.new_task_gen('cxx', 'program')
	p.target = 'main'
	p.source = ['main.cpp']

	foo = bld.new_task_gen('cxx', 'shlib')
	foo.target = 'foo'
	foo.source = ['foo.cpp']

def shutdown():
	pass
