/* ./packageneric/generic/detail/src/packageneric/package/meta-information.private.hpp.  Generated by configure.  */
/* see packageneric/+autogenerated/autotools/autoheader.private.hpp.in for the -- commented -- file generated from configure.ac by autoheader. */

///\file
///\brief packageneric configuration.
#pragma once



////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///\name source package meta information
///\{
	/// name of the source package
	#define PACKAGENERIC__PACKAGE__NAME "diversalis"
	/// description of the source package
	#define PACKAGENERIC__PACKAGE__DESCRIPTION "preprocessor definitions for use in preprocessor conditions in order to write platform-specific code"
	/// version of the source package
	#define PACKAGENERIC__PACKAGE__VERSION "0.0.118"
	/// major version number of the source package
	#define PACKAGENERIC__PACKAGE__VERSION__MAJOR 0
	/// minor version number of the source package
	#define PACKAGENERIC__PACKAGE__VERSION__MINOR 0
	/// patch version number of the source package
	#define PACKAGENERIC__PACKAGE__VERSION__PATCH 118
	/// distribution archive (e.g., unstable, testing, stable)
	#define PACKAGENERIC__PACKAGE__ARCHIVE "unstable"
	/// origin
	#define PACKAGENERIC__PACKAGE__ORIGIN "the psycle project http://psycle.sourceforge.net"
	/// copyright
	#define PACKAGENERIC__PACKAGE__COPYRIGHT "Copyright (C) 1999-2006 the psycledelics development team http://psycle.pastnotecut.org and http://psycle.sourceforge.net"
///\}




////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///\name stage paths (to be able to execute from the build dir without installing)
///\{
	/// relative path from the build dir to the source dir
	#define PACKAGENERIC__CONFIGURATION__STAGE_PATH__BUILD_TO_SOURCE "../../../../../../../../../../.."
///\}
