#!/bin/bash

##############################################################################
#
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2 of the License, or (at your option) any later version.
# Copyright (C) 2004-2005 Johan Boule <bohan.dyndns.org>
#
# \meta generic
# \meta standard gnu
#
##############################################################################

function main
{
	cd $(dirname $0) &&
	if test ! -f ../++build/doxygen/doxygen.configuration
	then
		../configure.wrapper --with-gui
	fi &&
	doxygen ../++build/doxygen/doxygen.configuration &&
	case "$OSTYPE" in
		msys)
			dot_options=-Gfontpath="$SYSTEMROOT/fonts"
		;;
		*)
			:
		;;
	esac &&
	dot $dot_options -Tpng ../++build/src/+modules.dependencies.dot > ../++build/pixmaps/modules.dependencies.png &&
	if $(echo $* | grep --silent -- --distribute)
	then
		cd ../++build &&
		tar --create --bzip2 --exclude doxygen/doxygen.configuration --file /tmp/$USER.doxygen.tar.bz2 doxygen &&
		source ../bin/map-local-user-account-name-to-remote-user-account-name .. &&
		${SCP:-scp} /tmp/$USER.doxygen.tar.bz2 $remote__user@$remote__host:/tmp/$remote__user.doxygen.tar.bz2 &&
		${SSH:-ssh} $remote__user@$remote__host <<-eof
			set -vx &&
			cd $remote__path &&
			rm --force doxygen --recursive &&
			umask 0001 &&
			tar --extract --bzip2 --touch --file /tmp/$remote__user.doxygen.tar.bz2 &&
			chmod u=rwx,g=rwsx,o=rx doxygen &&
			find doxygen -follow -type d -exec chmod u=rwsx,o=rx {} \; &&
			find doxygen -follow -type f -exec chmod u+rw,g+rw,o+r-w {} \; &&
			./update-timestamps
		eof
	fi
}

main "$@"
