#! /bin/bash

##############################################################################
#
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2, or (at your option) any later version.
# Copyright (C) 1999-2005 Psycledelics http://psycle.pastnotecut.org : Johan Boule
#
# autotools autogenerator plugin
# \meta generic
# \meta standard gnu
#
##############################################################################

function main
{
	local output=$PACKAGENERIC__OUTPUT/$PACKAGENERIC__SUBPATH &&
	mkdir --parents $output
} &&

main "$@"
