#! /bin/sh
. $PACKAGENERIC__ROOT/packageneric/generic/bin/posix.shell &&

##############################################################################
#
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2, or (at your option) any later version.
# copyright 1999-2006 johan boule <bohan@jabber.org>
# copyright 2004-2006 psycledelics http://psycle.pastnotecut.org
#
# autotools autogenerator plugin
#
# \meta generic
# \meta standard posix
#
##############################################################################

main()
{
	local output=$PACKAGENERIC__OUTPUT/$PACKAGENERIC__SUBPATH &&
	mkdir -p $output
} &&

main "$@"
