///\file
///\brief packageneric configuration for module psycoal
#pragma once
#include <packageneric/configuration.private.hpp>

#define PACKAGENERIC__MODULE__NAME "psycoal"
#define PACKAGENERIC__MODULE__VERSION__INTERFACE 0
#define PACKAGENERIC__MODULE__VERSION__INTERFACE__MININUM_COMPATIBLE 0
#define PACKAGENERIC__MODULE__VERSION__IMPLEMENTATION 0
#define PACKAGENERIC__MODULE__DESCRIPTION "psycle open audio library"
#define PACKAGENERIC__MODULE__SOURCE__PSYCLE__COAL__GEAR 1
#define PACKAGENERIC__MODULE__SOURCE__PSYCLE__COAL__ARRANGER 1
#define PACKAGENERIC__MODULE__SOURCE__PSYCLE__COAL__HOST 1
#define PACKAGENERIC__MODULE__SOURCE__PSYCLE__COAL__EVENT 1
