#! /bin/bash

##############################################################################
#
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2 of the License, or (at your option) any later version.
# Copyright (C) 2004-2005 Johan Boule <bohan.dyndns.org>
#
# \meta generic
# \meta standard posix
#
##############################################################################

set -o nounset &&

function main
{
	echo files: $(count-files) &&
	echo lines: $(count --lines) &&
	echo words: $(count --words)
} &&

function count
{
	cd $($(dirname $0)/root) &&
	local wc="${1:---words}" &&
	find src \( -name '*.cpp' -or -name '*.hpp' -or -name '*.hpp.in' \) \
	-exec wc $wc {} \; |
	sed 's/[^0-9]*//g' |
	xargs echo |
	sed 's/ / + /g' |
	xargs expr
} &&

function count-files
{
	cd $($(dirname $0)/root) &&
	find src \( -name '*.cpp' -or -name '*.hpp' -or -name '*.hpp.in' \) |
	wc --lines
} &&

main "$@"
