#!/bin/sh

###########################################################################
#
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2, or (at your option) any later version.
# copyright 2004-2007 psycledelics http://psycle.pastnotecut.org : johan boule
# copyright 2001,2002 Earnie Boyd  <earnie@users.sf.net>
#
# Environment initialization script for login shells
#
###########################################################################

if test -z "$MSYSTEM"
then
	MSYSTEM=MINGW32
fi

# I filter the PATH value setting in order to get ready for self hosting the
# MSYS runtime and wanting different paths searched first for files.
if test "$MSYSTEM" = MINGW32
then
	export PATH=/usr/local/bin:/opt/mingw/bin:/usr/bin:/bin:$PATH
else
	export PATH=/usr/local/bin:/usr/bin:/bin:/opt/mingw/bin:$PATH
fi

if test -z "$LOGNAME"
then
	LOGNAME=$(id --user --name || echo $USERNAME)
fi

if test -z "$USER"
then
	USER=$LOGNAME
fi

# Set up USER's home directory
if test -z "$HOME"
then
	HOME=/home/$USER
	if test ! -d "$HOME"
	then
		mkdir --verbose --parents "$HOME" ||
		{
			HOME=/tmp/no-home-dir-for-$USER &&
			mkdir --verbose --parents "$HOME" ||
			{
				HOME=/tmp &&
				test -d $HOME ||
				HOME=/
			}
		}
	fi
	cd "$HOME"
	if test "$HISTFILE" != "$HOME/.bash_history"
	then
		HISTFILE=$HOME/.bash_history
	fi
fi

export LOGNAME USER HOME HISTFILE MSYSTEM

for i in /etc/profile.d/*.sh
do
	if test -f $i
	then
		. $i
	fi
done

export MAKE_MODE=unix

# If shell is bash "Bourne Again SHell", and,
# if shell is interactive, then,
# we source the interactive config file 
if test -n "$BASH" -a -n "$PS1"
then
	# include /etc/bash.bashrc if it exists
	if test -f /etc/bash.bashrc
	then
		source /etc/bash.bashrc
	fi
fi
