#!/bin/bash

###########################################################################
#
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2, or (at your option) any later version.
# copyright 2004-2007 psycledelics http://psycle.pastnotecut.org : johan boule
#
# Verifies the signature of downloaded files
#
###########################################################################

function main
{
	local url=$1 && shift &&
	local download=/tmp/download.$$ &&
	rm --force --recursive $download &&
	mkdir $download &&

	wget --non-verbose --output-document $download/clear-signed $url &&
	$(dirname $0)/gpg.clear-signed-message.verify-signature-and-output-body gpg='gpgv --homedir /dev-pack/.gnupg' < $download/clear-signed
	
	: ||
	{	
		rm --force --recursive $download 2>/dev/null
		false
		return
	}
} &&

main "$@"
