#!/bin/bash

##############################################################################
#
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2 of the License, or (at your option) any later version.
# copyright 2003-2007 johan boule <bohan@jabber.org>
# copyright 2003-2007 psycledelics http://psycle.pastnotecut.org
#
# General-purpose: yes
#
# Lists c++ files which #include headers that are specific to an operating system.
#
##############################################################################

function main
{
	cd $(dirname $0)/.. &&
	find src \( -name '*.cpp' -or -name '*.hpp' -or -name '*.hpp.in' \) -and ! -name '+*' \
	-exec grep --extended-regexp --with-filename --line-number '#include <.*\.h>' {} \; |
	grep --extended-regexp --invert-match '#include <(g(lib|(d|t)k)|libgnomecanvas)mm/.*\.h>'
}

main "$@"
