#!/bin/bash

##############################################################################
#
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2 of the License, or (at your option) any later version.
# copyright 2004-2007 johan boule <bohan@jabber.org>
# copyright 2004-2007 psycledelics http://psycle.pastnotecut.org
#
# \meta generic
#
##############################################################################

function main
{
	cd $(dirname $0)/.. &&
	grep --color=$(test -t && echo always || echo auto) "\\meta $1" --recursive [^,]* | grep --invert-match {arch}
}

main "$@"
