#!/bin/bash

##############################################################################
#
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2, or (at your option) any later version.
# copyright 2003-2007 johan boule <bohan@jabber.org>
# copyright 2003-2007 psycledelics http://psycle.pastnotecut.org
#
# \meta generic
# \meta standard gnu
#
##############################################################################

function main
{
	cd $(dirname $0) &&
	find -follow -type f -perm +0100 -exec chmod u=rwx,g=rwx,o=r {} \;
	find -follow -type f ! -perm +0100 -exec chmod ug=rw,o=r {} \;
	find -follow -type d -exec chmod u=rwx,g=rwsx,o=rx {} \;
} &&

main "$@"
