#! /bin/bash

##############################################################################
#
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2 of the License, or (at your option) any later version.
# copyright 2003-2007 johan boule <bohan@jabber.org>
# copyright 2003-2007 psycledelics http://psycle.pastnotecut.org
#
# \meta generic
# \meta standard gnu
#
##############################################################################

set -o nounset &&

function main
{
	cd $($(dirname $0)/root) &&
	find src \( -name \*.cpp -or -name \*.hpp -or -name \*.hpp.in \)
} &&

main "$@"
