#pragma once
 
/* src/./universalis/operating_system/detail/microsoft/packageneric.microsoft.never-hardcoded.hpp. Generated automatically at end of configure. */
/* src/./universalis/operating_system/detail/microsoft/packageneric.microsoft.never-hardcoded.private.hpp.  Generated by configure.  */
/* see ./src/+autoheader.private.hpp.in for the -- commented -- file generated from configure.ac by autoheader. */

///\file
///\brief packageneric configuration, microsoft's only stuff.
#pragma once



////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///\name microsoft's only stuff
///\{

/// branch of the operating system.
/* #undef UNIVERSALIS__OPERATING_SYSTEM__MICROSOFT__PACKAGENERIC__CONFIGURATION__OPERATING_SYSTEM__MICROSOFT__BRANCH__NT */
/// major version number of the operating system.
#ifndef UNIVERSALIS__OPERATING_SYSTEM__MICROSOFT__PACKAGENERIC__CONFIGURATION__OPERATING_SYSTEM__MICROSOFT__VERSION__MAJOR 
#define UNIVERSALIS__OPERATING_SYSTEM__MICROSOFT__PACKAGENERIC__CONFIGURATION__OPERATING_SYSTEM__MICROSOFT__VERSION__MAJOR  5 
#endif
/// minor version number of the operating system.
#ifndef UNIVERSALIS__OPERATING_SYSTEM__MICROSOFT__PACKAGENERIC__CONFIGURATION__OPERATING_SYSTEM__MICROSOFT__VERSION__MINOR 
#define UNIVERSALIS__OPERATING_SYSTEM__MICROSOFT__PACKAGENERIC__CONFIGURATION__OPERATING_SYSTEM__MICROSOFT__VERSION__MINOR  1 
#endif
/// patch version number of the operating system.
/* #undef UNIVERSALIS__OPERATING_SYSTEM__MICROSOFT__PACKAGENERIC__CONFIGURATION__OPERATING_SYSTEM__MICROSOFT__VERSION__PATCH */
/// major version number of the internet explorer extra layer.
#ifndef UNIVERSALIS__OPERATING_SYSTEM__MICROSOFT__PACKAGENERIC__CONFIGURATION__OPERATING_SYSTEM__MICROSOFT__VERSION__EXTRA_LAYER__INTERNET_EXPLORER__MAJOR 
#define UNIVERSALIS__OPERATING_SYSTEM__MICROSOFT__PACKAGENERIC__CONFIGURATION__OPERATING_SYSTEM__MICROSOFT__VERSION__EXTRA_LAYER__INTERNET_EXPLORER__MAJOR  6 
#endif
/// minor version number of the internet explorer extra layer.
/* #undef UNIVERSALIS__OPERATING_SYSTEM__MICROSOFT__PACKAGENERIC__CONFIGURATION__OPERATING_SYSTEM__MICROSOFT__VERSION__EXTRA_LAYER__INTERNET_EXPLORER__MINOR */
/// patch version number of the internet explorer extra layer.
/* #undef UNIVERSALIS__OPERATING_SYSTEM__MICROSOFT__PACKAGENERIC__CONFIGURATION__OPERATING_SYSTEM__MICROSOFT__VERSION__EXTRA_LAYER__INTERNET_EXPLORER__PATCH */

///\}
 
