#!/bin/bash

##############################################################################
#
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2, or (at your option) any later version.
# Copyright (C) 1999-2005 Psycledelics http://psycle.pastnotecut.org : Johan Boule
#
# Converts the whole debian archive to other package formats
# \meta generic
# \meta standard gnu
#
##############################################################################

function main
{
	local packages=$1 &&
	local debian=$2

	cd $packages &&
		
	local formats="lsb tgz rpm" &&
	for format in $formats
	do
		local to="$to --to-$format"
	done &&

	fakeroot -- alien --keep-version $to $debian/*.deb &&

	mkdir --verbose linux-standard-base &&
	mv --verbose lsb-* linux-standard-base/ &&
	
	mkdir --verbose slackware &&
	mv --verbose *.tgz slackware/ &&
	
	mkdir --verbose rpm &&
	mv --verbose *.rpm rpm/
}

main "$@"
