///\file
///\brief configuration for diversalis, host unknown-microsoft-unknown.
/// This public configuration was not generated by an autoconfiguration script;
/// it was handwritten hardcoded for the following canonical host triplet:
/// - compiler: microsoft
/// - operating system: microsoft (it is unclear what other operating systems are supported by microsoft's compiler)
/// - architecture: it is unclear what architectures are supported by microsoft's compiler and operating system
#pragma once

#define DIVERSALIS__STDC_HEADERS  1 
#define DIVERSALIS__HAVE_STDINT_H  1 

#define DIVERSALIS__SIZEOF  
#define DIVERSALIS__SIZEOF__VOID_P  4 
#define DIVERSALIS__SIZEOF__LONG_LONG_INT  8 
#define DIVERSALIS__SIZEOF__LONG_INT  4 
#define DIVERSALIS__SIZEOF__INT  4 
#define DIVERSALIS__SIZEOF__SHORT_INT  2 
#define DIVERSALIS__SIZEOF__CHAR  1 
#define DIVERSALIS__HAVE_LONG_DOUBLE  1 
#define DIVERSALIS__SIZEOF__LONG_DOUBLE  12 
#define DIVERSALIS__SIZEOF__DOUBLE  8 
#define DIVERSALIS__SIZEOF__FLOAT  4 

#define DIVERSALIS__OPERATING_SYSTEM__BRANCH
#define DIVERSALIS__OPERATING_SYSTEM__BRANCH__NT
#define	DIVERSALIS__OPERATING_SYSTEM__VERSION__MAJOR 5
#define	DIVERSALIS__OPERATING_SYSTEM__VERSION__MINOR 1
#define	DIVERSALIS__OPERATING_SYSTEM__VERSION__PATCH 0
#define	DIVERSALIS__OPERATING_SYSTEM__VERSION__EXTRA_LAYER__INTERNET_EXPLORER__MAJOR 6
#define	DIVERSALIS__OPERATING_SYSTEM__VERSION__EXTRA_LAYER__INTERNET_EXPLORER__MINOR 0
#define	DIVERSALIS__OPERATING_SYSTEM__VERSION__EXTRA_LAYER__INTERNET_EXPLORER__PATCH 0
