#! /usr/bin/env waf

APPNAME = 'dummy'
VERSION = '0.0.0'

srcdir = '.'
blddir = '++build'

def init(): pass

def set_options(opt): pass

def configure(conf): pass

def build(bld):

	for path in ('dir', 'wscript'):
	
		node = bld.srcnode.find_resource(path)
		if node: print 'found resource', node
		else: print 'not found resource', path

		node = bld.srcnode.find_dir(path)
		if node: print 'found dir     ', node
		else: print 'not found dir     ', path
