#! /bin/bash

##############################################################################
#
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2, or (at your option) any later version.
# copyright 2002-2008 psycle development team http://psycle.sourceforge.net ; johan boule <bohan@jabber.org>
#
# On microsoft's operating system, we lack a software distribution system
# (This operating system is not a distribution, it's both proprietary and anarchic).
# So, this script creates a post install dir containing every bits of software needed
# so that we can distribute the dir as a self-contained raw binary package.
#
##############################################################################

function main
{
	local install=$1 && shift ||
	{
		echo-custom "$(basename $0): parameter expected: the directory containing the install tree." &&
		false
	} &&
	local post=$1 && shift ||
	{
		echo-custom "$(basename $0): parameter expected: the basename of the destination dir for the package tar." &&
		false
	} &&
	echo-custom "$(basename $0): Entering directory $install" &&
	cd $install &&
	rm --verbose --force --recursive $post &&
	mkdir --verbose $post &&
	if test -d bin
	then
		mv --verbose bin $post
	else
		mkdir --verbose $post/bin
	fi &&
	if test -d lib && ! rmdir --verbose lib 2>/dev/null
	then
		mv --verbose lib $post
	fi &&
	if test -d libexec && ! rmdir --verbose libexec 2>/dev/null
	then
		mv --verbose libexec $post
	fi &&
	if test -d share && ! rmdir --verbose share 2>/dev/null
	then
		mv --verbose share $post
	fi &&
	if test -d include && ! rmdir --verbose include 2>/dev/null
	then
		mv --verbose include $post
	fi &&
	dependencies $post &&
	split-debugging-information . &&
	echo-custom "$(basename $0): Standalone/self-contained binary distribution package is at $(pwd)/$post" &&
	echo-custom "$(basename $0): You can move and run this directory anywhere you want. The executables binaries are under the bin subdirectory." &&
	#(cd $(pwd) && start explorer .) &&
	echo-custom "$(basename $0): Completed successfully." ||
	{
		echo-custom "$(basename $0): Failed for $install/$post." &&
		false
	}
} &&

function dependencies
{
	local post=$1 && shift &&
	echo-custom "$(basename $0): Computing and bringing dependencies for $post ..." &&
	
	cp --verbose --recursive \
		$(which exchndl.dll) \
		$post/bin/ &&
				
	if cygcheck-fix-paths $(find $post/ \( -name \*.dll -or -name \*.exe \)) | grep -E --silent --ignore-case /libgdk-
	then
		cp --verbose --recursive \
			$(which gtkthemeselector) \
			$(which gtk2_prefs) \
			$post/bin/ &&
		local gtk=$(dirname $(pkg-config --libs-only-L $(pkg-config --list-all | grep -E ^gtk | sed 's/  *.*//') | sed 's/^-L//')) &&
		cp --verbose --recursive $gtk/etc $post &&
		cp-compound $gtk $post 'lib/pango/*/modules' &&
		cp-compound $gtk $post 'lib/gtk-*/*/'{immodules,loaders,engines} &&
		cp-compound $gtk $post share/themes &&
		cp-compound $gtk $post share/gtkthemeselector
	fi &&

	qt=$(cygcheck-fix-paths $(find $post/ \( -name \*.dll -or -name \*.exe \)) | grep -E --ignore-case '/qtgui[0-9]*\.dll') &&

	if test -n "$qt"
	then
		if test "$OSTYPE" = cygwin
		then
			qt=$(cygpath --unix "$qt")
		fi &&
		qt=$(dirname "$qt") &&
		qt=$(dirname "$qt") &&
		cp-compound "$qt" $post/bin/ 'plugins/*/*.dll'
	fi &&

	local system="$(echo $SYSTEMROOT | sed 's|\\|/|g')" &&

	cygcheck-fix-paths $(find $post/ \( -name \*.dll -or -name \*.exe \)) |
	(
		while read dep
		do
			if test -n "$dep"
			then
				if $(echo "$dep" | grep --silent --ignore-case "^$system")
				then
					echo-custom "$(basename $0): skipping system-wide (SYSTEMROOT environment variable) $dep"
				else
					if $(echo $dep | grep --silent --ignore-case ^$post/)
					then
						echo-custom "$(basename $0): skipping already in package $dep"
					else
						cp --verbose "$dep" $post/bin/
					fi
				fi
			fi ||
			return
		done
	)
} &&

function cygcheck-fix-paths
{
	cygcheck "$@" | sed 's|^ *||' | sed 's|\\|/|g' | sort -ub
} &&

function cp-compound
{
	local from=$1 && shift &&
	local to=$1 && shift &&
	(cd "$from" && echo "$@") |
	(
		while read compound
		do
			echo "$from/$compound" &&
			mkdir --verbose --parents "$to/$compound" &&
			cp --verbose --recursive "$from/$compound/*" "$to/$compound" ||
			return
		done
	)
} &&

function split-debugging-information
{
	return # disabled
	#################

	local pop=$(pwd) &&
	(
		cd $1 && shift &&
		echo-custom "$(basename $0): Splitting debugging information for $(pwd) ..." &&
		for binary in $(find . \( -name \*.dll -or -name \*.exe \))
		do
			#if test ! -d debuging-information/$(dirname $binary)
			#then
			#	mkdir --verbose --parents debuging-information/$(dirname $binary)
			#fi &&
			#objcopy --verbose --only-keep-debug $binary debuging-information/$binary.debugging-information &&
			#objcopy --verbose --strip-debug $binary &&
			#objcopy --verbose --add-gnu-debuglink=debuging-information/$binary.debugging-information $binary &&
	
			# --add-gnu-debuglink seems not to bo working... :-( ... well, let's just strip
	
			#objcopy --verbose --strip-unneeded $binary &&
			#strip --verbose --strip-unneeded $binary &&
	
			# --strip-unneeded seems not to be working... :-(
			
			#objcopy --verbose --strip-debug $binary &&
			#strip --verbose --strip-debug $binary &&
	
			# erm, neither --strip-debug :-(
	
			true || return
		done
	)
} &&

function echo-custom
{
	#echo -en '\e[1;36m' &&
	echo "$@" #&&
	#echo -en '\e[0m'
} &&

main "$@"
