#! /bin/sh

recurse()
{
	for x
	do
		case "$x" in
			*.la)
				recurse $(. $x && eval echo \$$what)
			;;
			*)
				echo $x
			;;
		esac
	done
} &&

main()
{
	what=$1 && shift &&
	recurse "$@"
}

main "$@"
