///@file
///@brief packageneric configuration for host unknown-microsoft-unknown, module universalis
/// This file was autogenerated by package/modules ; do not edit.
#pragma once
#include <packageneric/package/configurations/hardcoded/unknown-microsoft-unknown/configuration.private.hpp>
#include <packageneric/package/modules/lib.universalis/defines.private.hpp>
