///\file
///\brief configuration for diversalis, host unknown-microsoft-unknown.
/// This file was not autogenerated by autoconf's configure, but handwritten.
#pragma once

#define DIVERSALIS__STDC_HEADERS  1 
#define DIVERSALIS__HAVE_STDINT_H  1 

#define DIVERSALIS__SIZEOF  
#define DIVERSALIS__SIZEOF_VOID_P  4 
#define DIVERSALIS__SIZEOF_LONG_LONG_INT  8 
#define DIVERSALIS__SIZEOF_LONG_INT  4 
#define DIVERSALIS__SIZEOF_INT  4 
#define DIVERSALIS__SIZEOF_SHORT_INT  2 
#define DIVERSALIS__SIZEOF_CHAR  1 
#define DIVERSALIS__HAVE_LONG_DOUBLE  1 
#define DIVERSALIS__SIZEOF_LONG_DOUBLE  12 
#define DIVERSALIS__SIZEOF_DOUBLE  8 
#define DIVERSALIS__SIZEOF_FLOAT  4 
