#! /usr/bin/env python
# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2, or (at your option) any later version.
# copyright 2008-2008 members of the psycle project http://psycle.sourceforge.net ; johan boule <bohan@jabber.org>

import sys, os, os.path

import filesystem, cxx_include_scanner

if __name__ == '__main__':
	import time
	
	t0 = time.time()
	fs = filesystem.FileSystem()
	print >> sys.stderr, 'load time:', time.time() - t0

	t0 = time.time()
	scanner = cxx_include_scanner.IncludeScanner(fs)
	print >> sys.stderr, 'load time:', time.time() - t0

	#top = fs.src_node(os.path.join(os.path.dirname(__file__), 'laika'))
	top = fs.src_node(os.path.join(os.path.dirname(__file__), 'waf-test'))

	src_dirs = set(['src'])

	# get the dirs generated by genbench
	for d in top.actual_children:
		if d.startswith('src-'): src_dirs.add(d)

	for src in src_dirs:
		src = top.find(src)
		scanner.paths.add(src.abs_path)
		#foo = src.find('foo/foo.cpp')
		foo = fs.src_node(src.abs_path + '/foo/foo.cpp')
		main = fs.src_node(src.abs_path + '/main/main.cpp')
		for s in foo, main:
			changed = s.changed()
			print 'translation unit:', s.abs_path, '(changed: ' + str(changed) + ')'
			if changed:
				for dep in scanner.scan_deps(s.abs_path):
					dep = fs.declare(dep)
					print '\tdep:', dep.abs_path


	scanner.display()
	fs.display()

	t0 = time.time()
	scanner.dump()
	print >> sys.stderr, 'dump time:', time.time() - t0

	t0 = time.time()
	fs.dump()
	print >> sys.stderr, 'dump time:', time.time() - t0

if False:
	class LibFoo(Lib):
		def __init__(self, project):
			Lib.__init__(self, project, aliases = ['foo'])
			
		def dyn_in_tasks(self):
			if len(self.in_tasks): return None
			src = self.project.fs.src_node('src')
			foo = src.built_node('foo/foo.o')
			self.sources = [foo]
			obj = Obj(project)
			obj.target = foo
			self.in_tasks = [obj]
			for t in self.in_tasks:
				t.source = t.target.src_node_ext('.cpp')
				t.out_tasks = [self]
				
		def process(self):
			self.target = self.project.fs.built_node('libfoo.so')
			Lib.process(self)
			
	from project import Project
	project = Project()
	lib_foo = LibFoo(project)
